server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8443/realms/test/protocol/openid-connect/certs
#keycloak:
#  realm: javatechie
#  auth-server-url: http://localhost:8180/auth
#  resource: springboot-keycloak
#  public-client: true
#  bearer-only: true